site_name: FrappeAPI
theme:
  name: material
  palette:
    primary: deep purple
    accent: deep purple
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate

repo_name: 0xsirsaif/frappe-api
repo_url: https://github.com/0xsirsaif/frappe-api

nav:
  - Home: index.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/0xsirsaif/frappe-api
    - icon: fontawesome/brands/twitter
      link: https://x.com/0xsirsaif
