site_name: FrappeAPI
site_url: https://0xsirsaif.github.io/frappe-api/
theme:
  name: material
  palette:
    primary: deep purple
    accent: deep purple
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - content.code.copy

repo_name: 0xsirsaif/frappe-api
repo_url: https://github.com/0xsirsaif/frappe-api

nav:
  - FrappeAPI: index.md
  - Roadmap: roadmap.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/0xsirsaif/frappe-api
    - icon: fontawesome/brands/twitter
      link: https://x.com/0xsirsaif
